version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies...
      - sudo apt-get update -y
      - sudo apt-get install -y docker.io docker-compose
      - echo Docker and Docker Compose installed
  build:
    commands:
      - echo Building the Docker image...
      - docker-compose -f docker-compose.yml build
  post_build:
    commands:
      - echo Deployment completed successfully!

artifacts:
  files:
    - '**/*'
  discard-paths: yes
