version: 0.2
phases:
  install:
    commands:
      - echo Skipping ECR login, assuming IAM role-based authentication is enabled.
  pre_build:
    commands:
      - echo Building Docker image...
      - docker-compose build
  build:
    commands:
      - echo Tagging image...
      - docker tag my-flask-app:latest <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/my-flask-app:latest
      - echo Pushing image...
      - docker push <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/my-flask-app:latest
artifacts:
  files:
    - docker-compose.yml
    - Dockerfile

