version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
      bash -c "until mysql -h db -u root -ppassword -e 'select 1'; do echo Waiting for database; sleep 2; done; python app.py"  # wait for db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes: 
      - db_data:/var/lib/mysql 
volumes:
  db_data:
